apiVersion: apps/v1
kind: Deployment
metadata:
   name: gateway-deploy
spec:
   selector:
      matchLabels:
         myappname: mygateway
   replicas: 1
   template:            #This is the POD definition
      metadata:
         labels:
            myappname: mygateway
      spec:
         containers:
         - name: thegwcont
           image: richardchesterwood/k8s-fleetman-api-gateway:release1
           env:
           - name: SPRING_PROFILES_ACTIVE
             value: production-microservice
