apiVersion: v1
kind: Service
metadata:
   name: fleetman-api-gateway
spec:
   selector:
      myappname: mygateway
   ports:
      - name: gateway
        port: 8080
        targetPort: 8080

   type: ClusterIP

---

#apiVersion: v1
#kind: Service
#metadata:
#   name: fleetman-gatewaytest
#spec:
#   selector:
#      myappname: mygateway
#   ports:
#      - name: gatewaytest
#        port: 8080
#        targetPort: 8080
#        nodePort: 30880
#
#   type: NodePort

