apiVersion: v1
kind: Service
metadata:
   name: fleetman-mongodb
spec:
   selector:
      myappname: mymongo
   ports:
      - name: mongodb
        port: 27017
        targetPort: 27017

   type: ClusterIP