apiVersion: v1
kind: Service
metadata:
   name: fleetman-tracker
spec:
   selector:
      myappname: mytracker
   ports:
      - name: tracker
        port: 8080
        targetPort: 8080

   type: ClusterIP

---

#apiVersion: v1
#kind: Service
#metadata:
#   name: fleetman-trackertest
#spec:
#   selector:
#      myappname: mytracker
#   ports:
#      - name: trackertest
#        port: 8080
#        targetPort: 8080
#        nodePort: 30880

#   type: NodePort

