apiVersion: apps/v1
kind: Deployment
metadata:
   name: webapp-deploy
spec:
   selector:
      matchLabels:
         myappname: mywebapp
   replicas: 2
   template:            #This is the POD definition
      metadata:
         labels:
            myappname: mywebapp
      spec:
         containers:
         - name: webcontainer
           image: richardchesterwood/k8s-fleetman-webapp-angular:release2
           env:
           - name: SPRING_PROFILES_ACTIVE
             value: production-microservice