apiVersion: v1
kind: Service
metadata:
   name: fleetman-webapp
spec:
   #This defines which pods are going to be represented by this Service
   #The service becomes a network endpoint for other services or external 
   #users who wish to access the pod. In this instance, a browser
   selector:
      myappname: mywebapp
   ports:
      - name: http
        port: 80
        targetPort: 80
        nodePort: 30080

   type: NodePort